name: CI for Cloud IDE

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Test Client
      - name: Install dependencies for client
        working-directory: ./client # Set the working directory to client folder
        run: |
          npm install

      - name: Run tests for client
        working-directory: ./client
        run: |
          npm run test

      # Test Server
      - name: Install dependencies for server
        working-directory: ./server # Set the working directory to server folder
        run: |
          npm install

      - name: Run tests for server
        working-directory: ./server
        run: |
          npm run test
